#!/usr/bin/bash

mkdir ~/rs_tmp
cd ~/rs_tmp
eth1=0
eth2=0

ssh -i ~/.ssh/id_rsa.pub admin@mikrotik "ip dhcp-server lease print count-only where status=bound;interface monitor-traffic interface=ether1,ether2-master once" > mikr_band_tmp.txt

eth1=$(cat ~/rs_tmp/mikr_band_tmp.txt | grep fp-rx-bits-per-second | sed -e 's/ //g' -e 's/bps/;/g' -e 's/:/;/g' | cut -d ";" -f 2)
eth2=$(cat ~/rs_tmp/mikr_band_tmp.txt | grep fp-rx-bits-per-second | sed -e 's/ //g' -e 's/bps/;/g' -e 's/:/;/g' | cut -d ";" -f 3)

band=$(echo "$eth1 - $eth2" | bc)

echo "eth1=$eth1
eth2=$eth2
bandwidth=$band"

rm -r ~/rs_tmp
